version: '3'
services:
  ihanoi_be:
    container_name: ihanoi-be
    image: ihanoi-be
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_DBNAME=ecommerce
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - SEAWEED_MASTER_IP=http://localhost
      - SEAWEED_MASTER_PORT=9333
      - SERVER_PUBLIC_URL=https://api.cds.interits.vn
      - VNEID_API_KEY=${VNEID_API_KEY}
      - VNEID_CLIENT_ID=${VNEID_CLIENT_ID}
      - VNEID_CLIENT_SECRET=${VNEID_CLIENT_SECRET}
      - VNEID_TARGET_CODE=${VNEID_TARGET_CODE}
    ports:
      - "8000:8000"
    network_mode: host
#networks:
#  cds_my-network:
#    external: true