version: '3.9'

services:
  master:
    image: chrislusf/seaweedfs # use a remote image
    ports:
      - 9333:9333
      - 19333:19333
      - 9324:9324
    command: "-v=4 master -ip=master -ip.bind=0.0.0.0 -metricsPort=9324"
    volumes:
      - ./seaweed-data:/data
    networks:
      - ghtk

  volume:
    image: chrislusf/seaweedfs # use a remote image
    ports:
      - 8080:8080
      - 18080:18080
      - 9325:9325
    command: 'volume -mserver="master:9333" -ip.bind=0.0.0.0 -port=8080  -metricsPort=9325 -index=leveldb -publicUrl=localhost:8080'
    volumes:
      - ./seaweed-volume:/data
    depends_on:
      - master
    networks:
      - ghtk

  filer:
    image: chrislusf/seaweedfs # use a remote dev image
    ports:
      - 8888:8888
      - 18888:18888
    volumes:
      - ./seaweed-filer:/data
    command: '-v=4 filer -master="master:9333" -ip.bind=0.0.0.0'
    depends_on:
      - master
      - volume
    networks:
      - ghtk


networks:
  ghtk:
    external: true